Convert About UI content to Jetpack Compose
CruGlobal/godtools-android pull request #2295
Opened 2022-05-27 21:42 UTC by frett

- make it easy to enable jetpack compose for a module
- create a base GodToolsTheme for Compose
- create a new About screen layout using Compose
- use the new AboutLayout Composable instead of the AboutFragment

2022-05-27 21:50 UTC, frett commented on app/src/main/kotlin/org/cru/godtools/ui/about/AboutLayout.kt
> +@Composable
I'm not happy with having to annotate this function as `@Composable`, but it was necessary to be able to access `MaterialTheme.colorScheme.primary`.

2022-05-27 21:54 UTC, frett commented on app/src/main/kotlin/org/cru/godtools/ui/about/AboutLayout.kt
> +@Composable
whenever this gets moved to gto-support I might refactor out the linkStyle to get rid of the `@Composable` annotation. I'm sure at that point we will be more familiar with how `@Composable` works

2022-05-31 14:36 UTC, gyasistory requested changes
Looks good just a few comments and questions.

2022-05-31 14:36 UTC, gyasistory commented on app/src/main/kotlin/org/cru/godtools/ui/about/AboutLayout.kt
> +@Preview
```suggestion
@Preview(showBackground = true)
```
This will allow the white background to be visible in the preview.

2022-05-31 14:36 UTC, gyasistory commented on gradle/libs.versions.toml
> +androidx-compose = "1.2.0-beta02"
Why not use the release 1.1.1?

2022-05-31 14:36 UTC, gyasistory commented on ui/base/src/main/kotlin/org/cru/godtools/base/ui/theme/GodToolsTheme.kt
> +private val GT_BLUE = Color(0xFF3BA4DB)
```suggestion
private val GT_BLUE = colorResource(R.color.gt_blue)
```
You could use this to maintain the resource values.

2022-06-03 14:30 UTC, merged